# Ruff configuration for SHIOL-PLUS
# Baseline: enforce critical errors, relax style/whitespace until codebase is normalized

[lint]
select = ["F", "E", "W"]
ignore = [
  "E501", # line length handled later by formatter
  "W291", # trailing whitespace (temporary)
  "W293", # blank line contains whitespace (temporary)
  "F401", # unused imports (temporary for dynamic imports)
  "F811", # redefinition warnings (temporary)
  "F841", # local variable assigned but never used (temporary)
  "E402", # module level import not at top of file (temporary)
  "E701"  # multiple statements on one line (temporary)
]

# Limit to project modules
exclude = ["__pycache__", "data", "logs"]
