"""SHIOL+ v9 -- North Carolina Pick 3 game definition."""

GAME = {
    'id': 'pick3',
    'name': 'NC Pick 3',
    'active': True,
    'game_type': 'digit',
    'jurisdiction': 'NC',
    'digit_count': 3,
    'white_count': 3,
    'white_min': 0,
    'white_max': 9,
    'allow_duplicates': True,
    'has_extra_ball': False,
    'extra_max': None,
    'extra_name': None,
    'ticket_cost': 1.00,
    'draw_days': ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    'draw_time_et': '23:22',
    'cron_primary': ['0 5 * * *', '0 20 * * *'],
    'cron_backup': ['0 9 * * *'],
    'nc_web_url': 'https://nclottery.com/pick3',
    'data_sources': ['nc_lottery_csv', 'nc_web'],
    'nc_csv_url': 'https://nclottery.com/pick3-download',
    'nc_csv_date_format': '%m/%d/%Y',
    'nc_csv_columns': {
        'date': 0,
        'draw_time': 1,
        'n1': 2, 'n2': 3, 'n3': 4,
        'fireball': 5,
    },
    'prize_table': {
        3: ('straight', 500.0),
    },
    'compatible_strategies': ['random_baseline', 'frequency_weighted'],
    'description': 'NC Pick 3 -- sorteos diarios (Day & Evening). Tres dígitos del 0 al 9.',
    'logo_color': '#1a73e8',
}
