name: Deploy to Server (Light)

# This workflow runs automatically on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout latest code from GitHub
      - name: Get latest code
        uses: actions/checkout@v4

      # Step 2: Connect to server and update only what’s needed
      - name: Deploy to server (light)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/SHIOL-PLUS
            # Pull new changes from GitHub without resetting everything
            git pull origin main
            source venv/bin/activate
            # Update only required dependencies
            pip install --no-cache-dir -r requirements-prod.txt
            # Restart the service with the latest code
            sudo systemctl restart shiolplus.service
