name: Deploy to Server (Restart)

# This workflow runs only when triggered manually from GitHub Actions
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from GitHub
      - name: Get latest code
        uses: actions/checkout@v4

      # Step 2: Connect to the server and perform full reset + pipeline run
      - name: Deploy to server (restart + pipeline)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www
            # Clone the repo if it does not exist
            if [ ! -d "SHIOL-PLUS" ]; then
              git clone https://github.com/orlandobatistac/SHIOL-PLUS.git
            fi
            cd SHIOL-PLUS
            # Force sync with GitHub (clean reset)
            git fetch --all
            git reset --hard origin/main
            # Create virtual environment if missing
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            # Install production dependencies
            pip install --no-cache-dir -r requirements-prod.txt
            # Restart the systemd service
            sudo systemctl restart shiolplus.service
            # Run pipeline in background (rebuild DB, regenerate data, etc.)
            nohup python3 main.py --verbose > pipeline.log 2>&1 &
